before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
env:
  global:
    - secure: Ppln9Lh71AoZT0BpFejkBSGr/zw0a1uY8R05iDciYUD/6b9jhXo8hK2/qkgyCfPQeF6fvoQP/221NwN66C8PYiV0fWUdDkRSUuO46cVZh+ewnNbLl9570yOrgfC2pZfUl4eFIu/R85smSX+9wvMuU0QYS13vU04/KoIIxq/d3llBJ/is21ipgMJ3ZcaZv1Xa+QsILZpnPMuJpaA+eacHqEj5C1Dx70t81AQI21vfOJe1KOJm5UX9YOGDKAD5LHlTdXZqzTelZGq5/WXfmLLsV95YJlwa1J1isG6tlTRAW9bqUYqcQC5LofdYF7i9agWP1ZZVwVuuTik+5h0HuVEnWRpLM2zrYFrrjStZv/DxKHFOmo0TiDk1+5s0jCOYHJyj4OH44P3j0TdGJxwd5A0F4V3HpZvONAASv3JE/UJptgFQXJ+wOillspsvTfEYnlCEfi8gvfuObwmgQqAGP2qDpZTPcdhxyLU26WafSX9u6YEHs2T7gV+32IAIR/Z2KTrALA3yUcSGYNO/Q7LCYZs64bGjZKHJ+fZgAs4aAhmTrL0+9h9lP/x/oCciYojmCOwzdXwz4DTqI+R/OwS8AVKDTDG3ijldlrvXSs1pvpeLtU7Wodb+XJYUIKF2JnHSA3nKpkU4yX2unDeFrTdZB6cQK4id9mZNBrTnioYojChcdys=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
node_js:
  - 8
  - 11
